name: Deploy CICD Project done

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.CICD_SSH_KEY }}

      - name: Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@44.203.203.234 << 'EOF'
          set -e

          # Go to deployment directory
          cd /var/www/html/cicd-project 

          # Set Git safe directory
          sudo git config --global --add safe.directory /var/www/html/cicd-project

          # Save last successful commit
          LAST_COMMIT=$(git rev-parse HEAD)
          echo $LAST_COMMIT > /tmp/last_commit

          # Pull latest code
          sudo git checkout main

          sudo git pull origin main || {
            echo "Deployment failed, rolling back..."
            sudo git reset --hard $(cat /tmp/last_commit)
            exit 1
          }

          # Set ownership for Apache
          sudo chown -R www-data:www-data /var/www/html/cicd-project

          # Optional: restart Apache
          # sudo systemctl restart apache2

          EOF

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: false
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}

          subject: "Deployment Notification - CICD Project"

          body: |
            The deployment to the server has been successfully completed.

            Repository: ${{ github.repository }}
            Branch: ${{ github.ref }}
            Site URL: http://44.203.203.234

          to: rameezalee102@gmail.com
          from: rameezalee102@gmail.com
